### ISSUE TITLE
Access to linked videos?

### ISSUE THREAD

**Issue by MikeVioletAtOrbitalATK** [Open-MBEE/EMS-Webapp#13]
Hi, I am Mike Violet from Orbital ATK's Space Systems Group.  Over the summer we were finally able to get your MMS working here on our own server and are just starting to learn how to use it to support our system modeling efforts. We have downloaded the View Editor Users Guide, which has been helpful. However, the linked videos would make it much more useful. Unfortunately, since the videos are hosted on jpltube.jpl.nasa.gov/ it appears that we cannot access them. Can these videos be made available? 
Thanks in advance,
-Mike.

**Comment by shakeh** [comment]
Hi Mike, we have updated the documentation and removed all the videos. Take a look at the updates. If you have suggestions or need more detail on a specific feature please let us know.
