### ISSUE TITLE
grunt/bower behind proxy

### ISSUE THREAD

**Issue by cukii** [Open-MBEE/EMS-Webapp#2]
I'm having trouble running grunt behind a proxy. I was able to get away with for node by supplying the proxy as an input to npm install. I've exported the proxy settings in the linux environment, but that's not working either. Any suggestions?

**Comment by cukii** [comment]
My issue seemed to have been setting the proxy in bower. For future reference, here it is: http://bower.io/docs/config/

**Comment by clanier9** [comment]
Hey everyone, 

 

I was a summer intern last summer and have been receiving a lot of these messages lately. Can I be removed from the mailing list please? Thanks!

**Comment by cukii** [comment]
Looks like you're "watching" this repository:
https://github.com/Open-MBEE/EMS-Webapp/watchers

I think you just need to "unwatch" it on github.

**Comment by clanier9** [comment]
Thank you. I untied myself from the actual repo a while back but I guess it kept me as a watcher. Learn something new every day J
