### ISSUE TITLE
Grunt build fails

### ISSUE THREAD

**Issue by Enquier** [Open-MBEE/EMS-Webapp#4]
Output from Jenkins Console:

jquery-ui#1.11.4 bower_components/jquery-ui
└── jquery#2.1.4

angular-borderlayout#f5f9dfe226 bower_components/angular-borderlayout

jquery#2.1.4 bower_components/jquery

[4mRunning "html2js:main" (html2js) task[24m
Successfully converted [32m32[39m html templates to js.

[4mRunning "sass:dist" (sass) task[24m

[4mRunning "jshint:beforeconcat" (jshint) task[24m

[1m   src/directives/mmsTinymce.js[22m
     92 |[90m�� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
         ^ This character may get silently deleted by one or more browsers.
     92 |[90m�� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
         ^ Unexpected '�'.
    194 |[90m    �� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
            ^ This character may get silently deleted by one or more browsers.
    194 |[90m    �� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
             ^ Unexpected '�'.
    196 |[90m    �� �� �� �� �� �� �� �� $modalInstance.close(false);[39m
            ^ This character may get silently deleted by one or more browsers.
    196 |[90m    �� �� �� �� �� �� �� �� $modalInstance.close(false);[39m
             ^ Unexpected '�'.
    277 |[90m�� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
         ^ This character may get silently deleted by one or more browsers.
    277 |[90m�� �� �� �� �� �� �� �� $modalInstance.close(tag);[39m
         ^ Unexpected '�'.

[31m>> [39m8 errors in 68 files
[33mWarning: Task "jshint:beforeconcat" failed. Use --force to continue.[39m

[31mAborted due to warnings.[39m
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by lauraerinmann** [comment]
Pretty sure this is no longer a issue.
